# Generated by Django 5.2.4 on 2025-07-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videotranscript_remove_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
