# Generated by Django 5.2.4 on 2025-07-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_processed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoTranscript',
        ),
    ]
