# Generated by Django 5.2.4 on 2025-07-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_videotranscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='processed',
            field=models.BooleanField(default=True),
        ),
    ]
